apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: {{ .Release.Name }}-gateway
      containers:
        - name: gateway
          image: {{ .Values.image.registry }}/gateway:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- include "app.securityContext" . | nindent 10 }}
          ports:
            - containerPort: {{ .Values.gateway.port }}
          env:
            - name: OTEL_SERVICE_NAME
              value: gateway
            - name: SERVICE_PORT
              value: {{ .Values.gateway.port | quote }}
            - name: PRODUCT_SERVICE_URL
              value: "http://{{ .Release.Name }}-product:{{ .Values.product.port }}"
            - name: ORDER_SERVICE_URL
              value: "http://{{ .Release.Name }}-order:{{ .Values.order.port }}"
            - name: INVENTORY_SERVICE_URL
              value: "http://{{ .Release.Name }}-inventory:{{ .Values.inventory.port }}"
            {{- include "app.otelEnv" . | nindent 12 }}
            {{- include "app.chaosEnv" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.gateway.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.gateway.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
      protocol: TCP
  selector:
    app: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: gateway
    {{- include "app.labels" . | nindent 4 }}
